### ISSUE TITLE
Crashes with starshade simulation

### ISSUE THREAD

**Issue by mb2448** [dsavransky/EXOSIMS#25] opened 2017-02-22 22:17 UTC
I'm trying to run a starshade simulation case but running into a fatal error in the function `starprop` in _Observatory.py_.  The json file I am using is appended below, and the mission seed is ` 881634040`

When trying to execute the following code:

```
In [1]: import EXOSIMS,os.path
   ...: scriptfile = os.path.join(EXOSIMS.__path__[0],'scripts','starshade_testcase.json')
   ...: import EXOSIMS.MissionSim
   ...: sim = EXOSIMS.MissionSim.MissionSim(scriptfile)
In [2]: res = sim.SurveySimulation.run_sim()
```
The crash occurs on `
return r_star.to('km').reshape(currentTime.size,3)` in _Observatory.py_. 

There is an array mismatch error after the fifth iteration **_*** ValueError: total size of new array must be unchanged_**.  In particular, we have the following output for the first iterations:

> r_star size  2568
> currentTime size  856
> r_star size  1314
> currentTime size  438
> Current mission time:  1.0 d
> r_star size  3
> currentTime size  1
> r_star size  3
> currentTime size  1
> r_star size  3
> currentTime size  1
**> r_star size  2568
> currentTime size  1**

The bold text shows the error.  The `r_star` should be 3 times as large as the `currentTime` size for the vectors to match, but instead it is 2568 times as large.

json file used:

```
{
  "missionLife": 2.0,
  "missionPortion": 0.5,
  "ohTime": 0.1,
  "keepStarCatalog": true,
  "minComp": 0.1,
  "pupilDiam": 4,
  "obscurFac": 0,
  "dMagLim": 26,
  "telescopeKeepout": 60,
  "attenuation": 0.65,
  "intCutoff": 100.0,
  
  "settlingTime": 1.0, 
  "thrust": 450,
  "slewIsp": 4160,
  "scMass": 6000,
  "dryMass": 3400,
  "coMass":5800,
  "occulterSep":55000,
  "skIsp": 220,
  "defburnPortion":0.05,
  
  "ppFact": 0.1,
  "prange":[0.2, 0.2],
  "erange":[0, 0.01],
  "eta": 0.1,
  "arange":[0.75, 1.77],
  "Rprange":[1.0, 1.0],
  "Mprange":[1, 1],
  "scaleOrbits": true,
  "constrainOrbits": true,
  "scienceInstruments": [
    {
      "name": "imagingEMCCD",
      "focal": 120,
      "pitch": 5e-6,
      "QE": 0.999,
      "idark": 0.0,
      "CIC": 0,
      "sread": 0.0,
      "ENF": 1,
      "texp": 1000
    },
    {
      "name": "spectroEMCCD",
      "focal": 120,
      "pitch": 5e-6,
      "QE": 0.999,
      "idark": 0.0,
      "CIC": 0,
      "sread": 0.0,
      "ENF": 1,
      "texp": 1000,
      "Rs": 50
    }
  ],
  "starlightSuppressionSystems": [
    {
      "name": "Occulter_testcase",
      "occulter": true,

      "lam": 550,
      "IWA": 0.027,
      "OWA": 5.127,
      "ohTime": 0.0,
      "throughput": 0.2,
      "BW": 0.10,
      "occ_trans": 1.0,
      "occulterDiameter": 26,
      "NocculterDistances" :1,
      "occulterDistances": [
        {
        "occulterDistance": 55000,
        "occulterRedEdge": 690,
        "occulterBlueEdge": 450
        }
      ],
      "core_thruput": 0.69, 
      "core_contrast": 1.7880e-10
    }
 ],
      "observingModes": [
    {
      "instName": "imagingEMCCD",
      "systName": "Occulter_testcase",
      "detection": 1,
      "SNR": 7
    },
    {
      "instName": "spectroEMCCD",
      "systName": "Occulter_testcase",
      "SNR": 5
    }
  ],
  "modules": {
    "PlanetPopulation": "EarthTwinHabZone1",
    "StarCatalog": "EXOCAT1",
    "OpticalSystem": "KasdinBraems",
    "ZodiacalLight": "Stark",
    "BackgroundSources": "GalaxiesFaintStars",
    "PlanetPhysicalModel": " ",
    "Observatory": "WFIRSTObservatoryL2",
    "TimeKeeping": " ",
    "PostProcessing": " ",
    "Completeness": "BrownCompleteness",
    "TargetList": " ",
    "SimulatedUniverse": " ",
    "SurveySimulation": " ",
    "SurveyEnsemble": " "
  }
}

```

**Comment by turmon** [comment] 2017-02-23 23:11
I did not take the time to reproduce this exactly.  But it seems to occur when currentTime is updated and is made from a vector to a scalar.  Why does currentTime need to be a vector?  Is there any point in the code where there is more than one notion of the current time?
It would be possible to ensure that all updates to currentTime preserve its length.  This is not done now.

**Comment by ChrisDelaX** [comment] 2017-02-27 15:28
Thanks for this crash report. There is a bug in Observatory that I am aware
of and will fix today.

@Mike T: currentTime is supposed to be an array (even of size 1) its size
is compared to size of r_sc (1x3 or nx3) to determine which case we're in:
- case 1: we need the positions of 1 star (wrt obs) at 1 single time
- case 2: we need the positions of n stars at 1 single time
- case 3: we need the positions of n stars at n different times.
The case 3 will really happen only when using the starshade, because of
different slewtimes for each target, n different times for n different
targets.


2017-02-23 18:11 GMT-05:00 Michael Turmon <notifications@github.com>:

**Comment by ChrisDelaX** [comment] 2017-02-27 21:20
See my commit addressing this issue.
@mb2448: ^Mike Bottom, sorry for the typo. Could you let me know if I can close this issue?
I am also attaching the python file I used to test the Observatory modules. (TEST_OBS.py)
[TEST_OBS.py.txt](https://github.com/dsavransky/EXOSIMS/files/805028/TEST_OBS.py.txt)

**Comment by ChrisDelaX** [comment] 2017-02-27 21:36
After my last push, the SurveySimulation.run_sim() method should run without error.

**Closed** 2017-03-03 19:39 UTC

**Comment by rhondamorgan** [comment] 2017-03-06 19:45
I tested with the above json script and successfully ran to completion a single DRM with a star shade. Thanks for the fix!
