### ISSUE TITLE
koMap incorrect for same star in 2 different star catalogs

### ISSUE THREAD

**Issue by deanthedream** [dsavransky/EXOSIMS#264] opened 2021-03-02 19:57 UTC
It's not urgent, but it might be a good idea to update the public documentation of EXOSIMS to avoid any confusion. Stars are sometimes in one catalogue or another, with HIP label or without. That's why I wanted to try a large catalogue with all the RV and SL targets we have. Can someone remind me somewhere in EXOSIMS documentation on how to import SIMBAD catalogue in EXOSIMS? Or a sample script.

There is another reason why I was trying to load different catalogues (Let me loop Dean and Vanessa in): 

As you know, Vanessa and I are using EXOSIMS and CGI Perf to review some DRM targets. One feature that we would like to understand is why the same star in two different catalogues, with the same coordinates, gives rise to two completely different keep out results. This happens for two targets of a few we are using: HD 134987 and HD 219134. I was able to find HD 134987 in two catalogues: KnownRVPlanets and KeplerLike that Keith shared with me. In the first one, both seem to show 100% accessibility. In the Kepler on, HD 134987 shows 29.9% (closer to a first estimate of 38% based on some Vanessa's tool).

I attach the script that Dean shared with me and the two json scripts for each case. They run out of the box. I hope Dean, or someone, may take a look and let me know what you think. The coordinates agree quite well, although the star's distance is different (26.21 pc is compatible with SIMBAD or https://exoplanetarchive.ipac.caltech.edu, and 22.2 (I think http://exoplanet.eu/catalog/ jas that but it is down right now ...).

Hope I just missed something obvious. Many thanks!

Sergi

Short summary (longer at the end):

Notice that HIP 74500 = HD 134987

* Run with "test1":
Imported KeplerLikeUniverse (specific module) from EXOSIMS.SimulatedUniverse.KeplerLikeUniverse
Star HIP 74500 Completeness: 29.93 %
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    [(228.37051, -25.309164, 26.21)]>

* Run with "test2"
Imported KnownRVPlanetsUniverse (specific module) from EXOSIMS.Simulat[...]se.KnownRVPlanetsUniverse
...
Star HD 134987 Completeness: 100.00 %
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    [(228.36945, -25.309347, 22.2)]>

------------------------------------------------------------------
Full details:

#Run with "test1"

No-parallel: resetting SurveyEnsemble to Prototype
Imported SurveySimulation (prototype module) from EXOSIMS.Prototypes.SurveySimulation
Numpy random seed is: 504142085
Imported KeplerLikeUniverse (specific module) from EXOSIMS.SimulatedUniverse.KeplerLikeUniverse
Imported TargetList (prototype module) from EXOSIMS.Prototypes.TargetList
Imported EXOCAT1 (specific module) from EXOSIMS.StarCatalog.EXOCAT1
Imported Nemati (specific module) from EXOSIMS.OpticalSystem.Nemati
Imported Stark (specific module) from EXOSIMS.ZodiacalLight.Stark
Imported PostProcessing (prototype module) from EXOSIMS.Prototypes.PostProcessing
Imported GalaxiesFaintStars (specific module) from EXOSIMS.BackgroundSources.GalaxiesFaintStars
Imported Completeness (prototype module) from EXOSIMS.Prototypes.Completeness
Imported KeplerLike2 (specific module) from EXOSIMS.PlanetPopulation.KeplerLike2
Imported Forecaster (specific module) from EXOSIMS.PlanetPhysicalModel.Forecaster
Calculating target stellar masses.
Imported WFIRSTObservatoryL2 (specific module) from EXOSIMS.Observatory.WFIRSTObservatoryL2
Imported TimeKeeping (prototype module) from EXOSIMS.Prototypes.TimeKeeping
OBendTimes is: [1095.75] d
Limiting delta magnitude for mode syst: HLC-565 inst: imager is 25.510299866805603
Limiting delta magnitude for mode syst: SPC-660 inst: spectro is 22.25772487764565
Loading cached keepout map file from /Users/srhildeb/.EXOSIMS/cache/koMap_aed79454e49847afa8f95c13e5b95d3e.komap
Keepout Map loaded from cache.
Loading cached fZ from /Users/srhildeb/.EXOSIMS/cache/CompletenessTargetListNemati8d483cf138ace95805eba8c90c9e65b7.starkfZ
Loading cached fZQuads from /Users/srhildeb/.EXOSIMS/cache/CompletenessTargetListNemati8d483cf138ace95805eba8c90c9e65b7.fZmin
Imported SurveyEnsemble (prototype module) from EXOSIMS.Prototypes.SurveyEnsemble
/Users/srhildeb/opt/anaconda3/lib/python3.8/site-packages/erfa/core.py:154: ErfaWarning: ERFA function "utctai" yielded 1 of "dubious year (Note 3)"
  warnings.warn('ERFA function "{}" yielded {}'.format(func_name, wmsg),
Star HIP 74500 Completeness: 29.93 %
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    [(228.37051, -25.309164, 26.21)]>

# Run with "test2"

Imported KnownRVPlanetsUniverse (specific module) from EXOSIMS.Simulat[...]se.KnownRVPlanetsUniverse
Imported KnownRVPlanetsTargetList (specific module) from EXOSIMS.TargetList.KnownRVPlanetsTargetList
Imported EXOCAT1 (specific module) from EXOSIMS.StarCatalog.EXOCAT1
Imported Nemati_2019 (specific module) from EXOSIMS.OpticalSystem.Nemati_2019
Imported Stark (specific module) from EXOSIMS.ZodiacalLight.Stark
Imported PostProcessing (prototype module) from EXOSIMS.Prototypes.PostProcessing
Imported GalaxiesFaintStars (specific module) from EXOSIMS.BackgroundSources.GalaxiesFaintStars
Imported Completeness (prototype module) from EXOSIMS.Prototypes.Completeness
Imported KnownRVPlanets (specific module) from EXOSIMS.PlanetPopulation.KnownRVPlanets
Imported Forecaster (specific module) from EXOSIMS.PlanetPhysicalModel.Forecaster
/Users/srhildeb/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:748: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
Imported WFIRSTObservatoryL2 (specific module) from EXOSIMS.Observatory.WFIRSTObservatoryL2
Imported TimeKeeping (prototype module) from EXOSIMS.Prototypes.TimeKeeping
OBendTimes is: [1095.75] d
Limiting delta magnitude for mode syst: HLC-565 inst: imager is 25.510299866805603
Limiting delta magnitude for mode syst: SPC-660 inst: spectro is 22.25772487764565
Loading cached keepout map file from /Users/srhildeb/.EXOSIMS/cache/koMap_9e3965cda06ea5e5228afd0bde98832d.komap
Keepout Map loaded from cache.
Loading cached fZ from /Users/srhildeb/.EXOSIMS/cache/CompletenessKnownRVPlanetsTargetListNemati_2019cc51596884358bea5e0b264779aab39f.starkfZ
Loading cached fZQuads from /Users/srhildeb/.EXOSIMS/cache/CompletenessKnownRVPlanetsTargetListNemati_2019cc51596884358bea5e0b264779aab39f.fZmin
Imported SurveyEnsemble (prototype module) from EXOSIMS.Prototypes.SurveyEnsemble
/Users/srhildeb/opt/anaconda3/lib/python3.8/site-packages/erfa/core.py:154: ErfaWarning: ERFA function "utctai" yielded 1 of "dubious year (Note 3)"
  warnings.warn('ERFA function "{}" yielded {}'.format(func_name, wmsg),
Star HD 134987 Completeness: 100.00 %
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, pc)
    [(228.36945, -25.309347, 22.2)]>

**Comment by deanthedream** [comment] 2021-03-02 20:12
To check first: I looked at Prototypes/Observatory.py line ~555 where the cachename is defined for the keepout map. It looks like the Star Catalog is omitted from the cached filename for keepout maps. Adding in the star catalog name and universe name should be sufficient.

**Comment by deanthedream** [comment] 2021-03-02 20:22
#262 Added StarCatalog name to koMap cachedir

**Comment by hsergi** [comment] 2021-10-15 02:14
Hi Dean, is this issue resolved? We are going to deliver the Roman CGI ETC in 2 weeks from now (10/28) publicly.

**Comment by hsergi** [comment] 2021-10-17 22:48
I can't reproduce your example. It requires some FITS files in '$HOME/Documents/exosims/fitFilesFolder/HabExMay3/'. Hopefully, the pull request will be merged soon into master.

**Closed** 2022-10-20 21:04 UTC
