### ISSUE TITLE
Got error messages while running EXOSIMS under Python 2.7.12

### ISSUE THREAD

**Issue by jxie2016** [dsavransky/EXOSIMS#13] opened 2016-10-27 23:31 UTC
Got following error messages (ValueError: setting an array element with a sequence in /EXOSIMS/EXOSIMS/Prototypes/Observatory.py) while running EXOSIMS under Python 2.7.12.  

However, same script ran fine under Python 2.7.11.

![screen shot 2016-10-27 at 3 13 34 pm](https://cloud.githubusercontent.com/assets/23109788/19789104/c67f0cc2-9c61-11e6-8767-d80885fa478a.png)

**Comment by dsavransky** [comment] 2016-11-04 18:08
I am unable to reproduce the issue in any version of python.  Please attach the top level script you are running and supply versions for all package dependencies (in particular astropy and numpy as that appears to possibly be causing the issue).

Thanks.

**Comment by jxie2016** [comment] 2016-11-07 20:08
Hi, 
We are using:
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)

Here are the scripts I used:
[template_rpateltest_KnownRV_2years_json.txt](https://github.com/dsavransky/EXOSIMS/files/576520/template_rpateltest_KnownRV_2years_json.txt)

[Joan_EXOSIMS_end2end_py.txt](https://github.com/dsavransky/EXOSIMS/files/576517/Joan_EXOSIMS_end2end_py.txt)

Thanks, 
Joan

**Comment by ChrisDelaX** [comment] 2017-01-19 21:49
Hi Joan,
I tried to run a simulation using your json script attached, and I didn't get an error.
Do you still get the same error? If yes, this might be a compatibility issue. 
What's your version of astropy and numpy?
I would advice you run an update of anaconda using: conda update astropy
This should bring you to: python 2.7.13 , astropy 1.3 , numpy 1.11.2
Let me know if that helped.
Christian

**Comment by jxie2016** [comment] 2017-01-19 22:02
Hi, Christian

Thanks for your effort! Later I found the error was due to missing 
jplephem 2.5 on our server. After installing it, the script runs fine.

Best regards,

Joan

**Comment by ChrisDelaX** [comment] 2017-01-19 22:05
I'm glad this is solved.

**Comment by dsavransky** [comment] 2017-01-20 14:45
So, this points to an issue with the planet propagators that run when jplephem is not found.  Need to keep this open until we figure out what's happening there.

**Comment by ChrisDelaX** [comment] 2017-01-20 21:11
I was able to reproduce the bug using "forceStaticEphem": true. 
I found the origin of the bug and was able to fix it. Then, I tested the template scripts and everything is looking fine. Closing the issue.

**Closed by ChrisDelaX** 2017-01-20 21:11 UTC
