### ISSUE TITLE
Singular matrix issue with WFIRSTL2

### ISSUE THREAD

**Issue by astropatel** [dsavransky/EXOSIMS#22] opened 2017-02-11 20:42 UTC
We've run into an interesting issue. When using WFIRSTObservatoryL2.py for the Observatory, we run into a singular matrix error when an interpolation is attempted using the L2_halo_orbit_six_month_v2.p file. The error is in the image attached.

  What is odd is that when tried on two other machines, (mine and Joan's) we don't see the error, and the code runs fine. It's just on the WFIRST dev site at IPAC that this issue persists. I am thinking it's cause of an older LAPACK/BLAS version. Do you see any way around this (perhaps the pickle file might be upgraded to circumvent any singular matrix calculation)?

![singularmatrix](https://cloud.githubusercontent.com/assets/3648312/22857218/d8e8a8b2-f055-11e6-80bc-7d875dd63a91.png)

**Comment by dsavransky** [comment] 2017-02-12 01:48
We've literally just hit this problem this week on our end on a single linux box and have been unable to reproduce it yet on any other machine.  Can you post the scipy version, how it was installed and (if available) the dependency versions?

**Comment by astropatel** [comment] 2017-02-13 01:13
So, we've tested it on three different machines. Mine (Mac, scipy 0.18.0) , Joan's (Mac, scipy 0.17.0) and the WFIRST Dev (Linux, scipy 0.17.0 and later upgraded to 0.18.0). No matter which of these scipy versions, only the WFIRST dev linux machine seems to fail.  They use conda, and I don't (pip install), so I'm guessing it's how conda packages and updates the LAPACK and BLAS packages.

I've attached two textfiles that show comparisons of the LAPACK and BLAS installations on all 3 machines, and python package installations on mine and the WFIRST dev machine. Let me know if more info is needed. :) 
[python_packages_comparison.txt](https://github.com/dsavransky/EXOSIMS/files/769851/python_packages_comparison.txt)
[lapack_versions.txt](https://github.com/dsavransky/EXOSIMS/files/769852/lapack_versions.txt)

**Comment by jxie2016** [comment] 2017-02-13 21:04
I used Anaconda on my laptop.

**Comment by astropatel** [comment] 2017-02-16 20:06
Would it sufficient to use the WFIRSTObservatory module instead of the L2 one as a temporary circumvention? Or even leaving the Observatory module designation in the json script blank?

**Comment by dsavransky** [comment] 2017-02-16 20:07
@deanthedream has supplied a fix and pull for this.  We just need to run one test offline before merging.  In the meantime, you can use a different observatory module, but it'll put the observatory on a non-cirum-L2 orbit.

**Comment by ChrisDelaX** [comment] 2017-03-03 20:36
@astropatel: Rahul, do you still get that issue on your side?

**Comment by dsavransky** [comment] 2017-03-08 15:02
Closing due to un-reproducibility with current code.  Will reopen as necessary.

**Closed by dsavransky** 2017-03-08 15:02 UTC
Labels: bug
